class SearchInfo:
    def __init__(self):
        self.playlist = ""
        self.title = ""
        self.album_title = ""
        self.genre = ""
        # self.language = ""
        self.performer = ""
        self.composer = ""
        self.publisher = ""
        self.modified_by = ""
        self.picture_artist = ""
        self.text_author = ""
        self.original_title = ""
        self.original_album_title = ""
        self.original_performer = ""
        self.original_composer = ""
        self.original_publisher = ""
        self.original_text_author = ""
        self.isrc = ""